apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-whoami-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-whoami
  template:
    metadata:
      labels:
        app: canary-whoami
    spec:
      containers:
      - name: whoami
        image: emilevauge/whoami
        ports:
        - containerPort: 80
